import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* basic common layout  */}
        <h1 className="relative flex text-center text-3xl justify-center p-2 bg-gray-600 text-white">
          Next JS APP
        </h1>
        {children}
      </body>
    </html>
  );
}
