import "../../src/app/globals.css";
import { Toaster } from "react-hot-toast";
import NavigationBar from "./components/NavigationBar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`m-0 p-0 font-poppins`}>
        <NavigationBar />
        {children}
        <Footer />
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
