import ClientLayout from "./ClientLayout";
import "../../src/app/globals.css";

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 p-0 font-poppins flex flex-col min-h-screen">
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
