import "../../src/app/globals.css";
import Head from "next/head";
import { AuthProvider } from "../../src/app/context/AuthContext";
import ClientLayout from "./ClientLayout";

export const metadata = {
  title: "Ecommerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </Head>
      <body className="m-0 p-0 font-poppins flex flex-col min-h-screen">
        <AuthProvider>
          <ClientLayout>{children}</ClientLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
